### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by Skippern** [openstreetview/upload-scripts#23]
The dependency `cookie jar` (`import http.cookiejar`) is not in the `requirements.txt` archives. Please revise all `requirements.txt` and add all dependencies.

**Comment by Skippern** [comment]
Same goes for `urllib.request`, it is not clear to me what module to install, so I am not able to run the script for the moment. have several `urllib` versions installed, plus a few modules derived from `urllib`

**Comment by james2432** [comment]
Do you have python3? Because that sound like you trying to run it on python2, scripts are only compatible with python3

**Comment by james2432** [comment]
It's in the readme as well: https://github.com/openstreetview/upload-scripts/blob/master/README.md#requirements-1

**Comment by Skippern** [comment]
Tried with python 2.7, 3.4, 3.5 and 3.6, installed all dependencies for all versions. Had a discussion on it on Brazilian telegram, and will try to install virtualenv to see if I can get this sorted.

BTW Using Mac OS X El Capitan

Aun Johnsen

**Comment by james2432** [comment]
Cookiejar is a standard lib in python3....maybe your installation is corrupt: https://docs.python.org/3.3/library/http.cookiejar.html

**Comment by Skippern** [comment]
The cookiejar error I have managed to solve, it is urllib.request that I can’t get around, but reading the dump seems it relates to site.

Aun Johnsen

**Comment by Skippern** [comment]
This is the current error message, I have just uninstalled and reinstalled completely python3 via port (MacPort package manager)
`
Failed to import the site module
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site.py", line 554, in <module>
    main()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site.py", line 540, in main
    known_paths = addusersitepackages(known_paths)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sysconfig.py", line 566, in get_config_vars
    import _osx_support
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/_osx_support.py", line 4, in <module>
    import re
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 335, in <module>
    import copyreg
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/copyreg/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
`

**Comment by james2432** [comment]
Python3 is trying to run python2 modules: 
<module> import copyreg File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/copyreg/__init__.py", line 7, in <module>

**Comment by Skippern** [comment]
I am reporting this as a bug to MacPorts, to see if they have a solution or a fix for this.

**Comment by james2432** [comment]
Do you have anything weird in your path variable?

**Comment by Skippern** [comment]
`PYTHONPATH=:/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python:/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages`

**Comment by james2432** [comment]
Yeah, if you have python3, you should have python2.7 in the path..

**Comment by Skippern** [comment]
Usually run my own stuff, and most scripts I have are py2.7, I'll add up py3 to the path

**Comment by Skippern** [comment]
It works when removing all py2.7 elements from the path and keep py3, when having both py2.7 and py3 in the path it falls back on that previous error. But now I have a different run error issue:

`Traceback (most recent call last):
  File "./osc_upload-scripts/upload_photos_by_exif/upload_photos_by_exif.py", line 489, in <module>
    main(sys.argv[1:])
  File "./osc_upload-scripts/upload_photos_by_exif/upload_photos_by_exif.py", line 350, in main
    photos_path = sorted(os.listdir(path), key=os.path.getmtime)
FileNotFoundError: [Errno 2] No such file or directory: 'toOSC/20161205183432/'`

**Comment by bogdan-telenav** [comment]
You need to provide full path do the directory.

**Comment by james2432** [comment]
Also if you have spaces in path you need to escape them

**Comment by Skippern** [comment]
It is uploading now, but I will still have to figure out how to deal with $PYTHONPATH, I need to have both 2.7 and 3 elements in it

**Comment by Skippern** [comment]
found a workaround, made a separate $PYTHON3PATH environmental variable, and run the uploads through scripts. I know it is dirty, but it works
